version: 2
jobs:
  build:
    docker: 
      - image: circleci/node:12.6-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}-{{ checksum "./progress/angular/components/package.json" }}-{{ checksum "./progress/react/package.json" }}
          - v1-dependencies-
      - run: 
          name: Install Dependencies
          command: |
            yarn install
            cd progress/react
            yarn install
            cd ../angular/components
            yarn install
            cd ../demos/
            cd ../../..
      - run:
          name: Install Dev Dependencies
          command: |
            yarn install --dev
            cd progress/react
            yarn install --dev
            cd ../angular/components
            yarn install --dev
            cd ../../..
      - save_cache:
          paths:
            - node_modules
            - progress/react/node_modules
            - progress/angular/components/node_modules
          key: v1-dependencies-{{ checksum "package.json" }}-{{ checksum "./progress/angular/package.json" }}-{{ checksum "./progress/react/package.json" }}
      - run:
          name: Build Packages
          command: yarn build
      - run:
          name: Verify SVG Build Artifacts
          command: yarn test:svg
      - run:
          name: Verify Progress Icon Build Artifacts
          command: |
            cd progress
            yarn build:all
            cd ..
            yarn test:progress
      - run:
          name: Test progress icon utility functions
          command: |
            cd progress
            yarn test:functions